services:
  encointer-node-bootstrap-community:
    image: "encointer/encointer-client-notee:1.3.3-for-tee"
    container_name: encointer-node-bootstrap-community
    depends_on: ['encointer-node']
    networks:
      - encointer-test-network
    command: bootstrap_demo_community.py -u ws://encointer-node -p 9912"
    restart: "no"
  demo-private-community:
    image: encointer-cli:dev
    container_name: encointer-private-community-demo
    build:
      context: ..
      dockerfile: build.Dockerfile
      target: deployed-client
    depends_on: ['encointer-node', 'encointer-worker-1', 'encointer-worker-2', 'encointer-node-bootstrap-community:condition:service_completed_successfully']
    networks:
      - encointer-test-network
    entrypoint: "dockerize -wait http://encointer-worker-2:4646/is_initialized -timeout 250s
      /usr/local/worker-cli/demo_private_community.sh -p 9912 -A 2011 -B 2012 -u ws://encointer-node
      -V wss://encointer-worker-1 -W wss://encointer-worker-2 -C /usr/local/bin/integritee-cli 2>&1"
    restart: "no"
networks:
  encointer-test-network:
    driver: bridge