services:
  demo-indirect-invocation:
    image: encointer-cli:dev
    container_name: integritee-indirect-invocation-demo
    build:
      context: ..
      dockerfile: build.Dockerfile
      target: deployed-client
    depends_on:
      encointer-node:
        condition: service_healthy
      encointer-worker-1:
        condition: service_healthy
      encointer-worker-2:
        condition: service_healthy
    environment:
      - RUST_LOG=warn,ws=warn,itc_rpc_client=warn
    networks:
      - encointer-test-network
    entrypoint: "/usr/local/worker-cli/demo_indirect_invocation.sh -p 9912 -u ws://encointer-node
      -V wss://encointer-worker-1 -A 2011 -W wss://encointer-worker-2 -B 2012 -C /usr/local/bin/integritee-cli 2>&1"
    restart: "no"
networks:
  encointer-test-network:
    driver: bridge