services:
  demo-sidechain:
    image: encointer-cli:dev
    container_name: integritee-sidechain-demo
    build:
      context: ..
      dockerfile: build.Dockerfile
      target: deployed-client
    depends_on:
      encointer-node:
        condition: service_healthy
      encointer-worker-1:
        condition: service_healthy
      encointer-worker-2:
        condition: service_healthy
    networks:
      - encointer-test-network
    entrypoint: "/usr/local/worker-cli/demo_sidechain.sh -p 9912 -A 2011 -B 2012 -u ws://encointer-node
      -V wss://encointer-worker-1 -W wss://encointer-worker-2 -C /usr/local/bin/integritee-cli 2>&1"
    restart: "no"
networks:
  encointer-test-network:
    driver: bridge