services:
  encointer-node:
    image: "encointer/encointer-node-notee:1.3.3-for-tee"
    container_name: encointer-node
    environment:
      - RUST_LOG=error
    networks:
      - encointer-test-network
    command: --dev --enable-offchain-indexing true --rpc-methods unsafe --ws-external --rpc-external --ws-port 9912
    #logging:
      #driver: local
  encointer-worker-1:
    image: encointer-worker:dev
    container_name: encointer-worker-1
    build:
      context: ..
      dockerfile: build.Dockerfile
      target: deployed-worker
    depends_on: ['encointer-node']
    environment:
      - RUST_LOG=warn,ws=warn,sp_io=warn,substrate_api_client=warn,jsonrpsee_ws_client=warn,jsonrpsee_ws_server=warn,enclave_runtime=warn,integritee_service=warn,ita_stf=warn
    networks:
      - encointer-test-network
    entrypoint: "dockerize -wait tcp://encointer-node:9912 -timeout 30s
      /usr/local/bin/integritee-service --clean-reset --ws-external -M encointer-worker-1 -T wss://encointer-worker-1
      -u ws://encointer-node -U ws://encointer-worker-1 -P 2011 -w 2101 -p 9912 -h 4645
      run --dev --skip-ra"
    restart: "no"
  encointer-worker-2:
    image: encointer-worker:dev
    container_name: encointer-worker-2
    build:
      context: ..
      dockerfile: build.Dockerfile
      target: deployed-worker
    depends_on: ['encointer-node', 'encointer-worker-1']
    environment:
      - RUST_LOG=warn,ws=warn,sp_io=warn,substrate_api_client=warn,jsonrpsee_ws_client=warn,jsonrpsee_ws_server=warn,enclave_runtime=warn,integritee_service=warn,ita_stf=warn
    networks:
      - encointer-test-network
    entrypoint: "dockerize -wait http://encointer-worker-1:4645/is_initialized -timeout 150s
      /usr/local/bin/integritee-service --clean-reset --ws-external -M encointer-worker-2 -T wss://encointer-worker-2
      -u ws://encointer-node -U ws://encointer-worker-2 -P 2012 -w 2102 -p 9912 -h 4646
      run --dev --skip-ra --request-state"
    restart: "no"
  encointer-node-bootstrap-community:
    image: "encointer/encointer-client-notee:1.3.3-for-tee"
    container_name: encointer-node-bootstrap-community
    depends_on: ['encointer-node', 'encointer-worker-1', 'encointer-worker-2']
    networks:
      - encointer-test-network
    entrypoint: "./entryscript.sh bootstrap_demo_community.py -u ws://encointer-node --port 9912"
    restart: "no"
networks:
  encointer-test-network:
    driver: bridge