services:
  worker-ping:
    image: worker-ping:dev
    build:
      context: .
      dockerfile: ping.Dockerfile
    depends_on: [ 'encointer-node', 'encointer-worker-1', 'encointer-worker-2' ]
    networks:
      - encointer-test-network
    #entrypoint: "ping encointer-worker-2 | while read pong; do echo \"$$(date): $$pong\"; done"
    entrypoint: "ping encointer-worker-2"
  pumba-network-delay:
    image: integritee-fork-producer:dev
    build:
      context: .
      dockerfile: fork.Dockerfile
    depends_on: [ 'encointer-node', 'encointer-worker-1', 'encointer-worker-2' ]
    networks:
      - encointer-test-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: "dockerize -wait http://encointer-worker-2:4646/is_initialized -timeout 250s
     pumba --interval 3m netem --interface eth0 --duration 30s delay --time 1000 encointer-worker-2"
networks:
  encointer-test-network:
    driver: bridge